## Numpy

In [ ]:
import numpy as np

In [ ]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
a = np.array([10, 30, 20, 4, 30, 50, 8, 100, 89, 90])
a[4]

30

In [ ]:
a[3:]

array([  4,  30,  50,   8, 100,  89,  90])

In [ ]:
a[3:7]

array([ 4, 30, 50,  8])

In [ ]:
a[1::4]

array([30, 50, 90])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones( (4, 5) )

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
type(np.ones((4, 5)))

numpy.ndarray

**Intervalo: 3 a 10, Cantidad de números: 5**

In [ ]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [ ]:
b = np.array( [ ['x', 'y', 'z'] , ['a', 'b' , 'e']  ] )

In [ ]:
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'e']]


numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [ ]:
cabeceras = [ ('nombre', 'S10'), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.full( (3, 5), 10 )

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.diag( [1, 3, 9, 10] )

array([[ 1,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

## Pandas

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series( [15, 20, 15, 20, 31] )

In [ ]:
series

0    15
1    20
2    15
3    20
4    31
dtype: int64

In [ ]:
type(series)

pandas.core.series.Series

In [ ]:
series[3]

20

In [ ]:
cat = pd.Series( ['p', 'l', 'a', 't', 'z', 'i'] )

In [ ]:
cat

0    p
1    l
2    a
3    t
4    z
5    i
dtype: object

In [ ]:
lst = ['Hola', 'mundo', 'robotico']
df = pd.DataFrame(lst)

In [ ]:
print(df)

          0
0      Hola
1     mundo
2  robotico


In [ ]:
data = {'Nombre' : ['Juan', 'Ana', 'Jose', 'Arturo'], 
        'Edad' : [25, 18, 23, 27],
        'Pais': ['MX', 'CO', 'BR', 'MX']} 

In [ ]:
data

{'Edad': [25, 18, 23, 27],
 'Nombre': ['Juan', 'Ana', 'Jose', 'Arturo'],
 'Pais': ['MX', 'CO', 'BR', 'MX']}

In [ ]:
df = pd.DataFrame(data)
df

Nombre  Edad Pais
0    Juan    25   MX
1     Ana    18   CO
2    Jose    23   BR
3  Arturo    27   MX

In [ ]:
print( df[ ['Nombre', 'Pais'] ] )

   Nombre Pais
0    Juan   MX
1     Ana   CO
2    Jose   BR
3  Arturo   MX


## Canciones

In [ ]:
data = pd.read_csv('canciones-2018.csv')

In [ ]:
data.head(5)

id  ... time_signature
0  6DCZcSspjsKoFjzjrWoCd  ...            4.0
1  3ee8Jmje8o58CHK66QrVC  ...            4.0
2  0e7ipj03S05BNilyu5bRz  ...            4.0
3  3swc6WTsr7rl9DqQKQA55  ...            4.0
4  2G7V7zsVDxg1yRsu7Ew9R  ...            4.0

[5 rows x 16 columns]

In [ ]:
artista = data.artists
artista[5]

'Post Malone'

In [ ]:
info = data.iloc[15]
info

id                     3GCdLUSnKSMJhs4Tj6CV3
name                All The Stars (with SZA)
artists                       Kendrick Lamar
danceability                           0.698
energy                                 0.633
key                                        8
loudness                              -4.946
mode                                       1
speechiness                           0.0597
acousticness                          0.0605
instrumentalness                    0.000194
liveness                              0.0926
valence                                0.552
tempo                                 96.924
duration_ms                           232187
time_signature                             4
Name: 15, dtype: object

In [ ]:
data.tail()

id  ... time_signature
95  630sXRhIcfwr2e4RdNtjK  ...            4.0
96  2xmrfQpmS2iJExTlklLoA  ...            4.0
97  5WvAo7DNuPRmk4APhdPzi  ...            5.0
98  1j4kHkkpqZRBwE0A4CN4Y  ...            4.0
99  3EPXxR3ImUwfayaurPi3c  ...            4.0

[5 rows x 16 columns]

In [ ]:
data.shape

(100, 16)

In [ ]:
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [ ]:
data['tempo'].describe()

count    100.000000
mean     119.904180
std       28.795984
min       64.934000
25%       95.730750
50%      120.116000
75%      140.022750
max      198.075000
Name: tempo, dtype: float64

In [ ]:
data.sort_index(axis = 0, ascending = False)

id  ... time_signature
99  3EPXxR3ImUwfayaurPi3c  ...            4.0
98  1j4kHkkpqZRBwE0A4CN4Y  ...            4.0
97  5WvAo7DNuPRmk4APhdPzi  ...            5.0
96  2xmrfQpmS2iJExTlklLoA  ...            4.0
95  630sXRhIcfwr2e4RdNtjK  ...            4.0
..                    ...  ...            ...
4   2G7V7zsVDxg1yRsu7Ew9R  ...            4.0
3   3swc6WTsr7rl9DqQKQA55  ...            4.0
2   0e7ipj03S05BNilyu5bRz  ...            4.0
1   3ee8Jmje8o58CHK66QrVC  ...            4.0
0   6DCZcSspjsKoFjzjrWoCd  ...            4.0

[100 rows x 16 columns]

## Reto 1
Tomar tres columnas favoritas y ordenarlas de for ascendente

In [ ]:
data[ ['artists', 'acousticness', 'time_signature'] ].sort_values(by = 'acousticness', axis = 0, ascending = True)

artists  acousticness  time_signature
82  Kendrick Lamar      0.000282             4.0
19      BlocBoy JB      0.001040             4.0
24        Dua Lipa      0.002610             4.0
58    Lil Uzi Vert      0.002640             4.0
81           Migos      0.002990             4.0
..             ...           ...             ...
99      Dean Lewis      0.697000             4.0
84      Ed Sheeran      0.779000             3.0
94    XXXTENTACION      0.847000             4.0
38    XXXTENTACION      0.883000             4.0
80   Billie Eilish      0.934000             4.0

[100 rows x 3 columns]

In [ ]:
data[ ['artists', 'acousticness'] ].sort_index(axis = 0, ascending = True)

artists  acousticness
0          Drake        0.0332
1   XXXTENTACION        0.2580
2    Post Malone        0.1170
3    Post Malone        0.5800
4          Drake        0.0589
..           ...           ...
95     Zac Efron        0.0716
96  Clean Bandit        0.2450
97     DJ Khaled        0.0733
98          ZAYN        0.1010
99    Dean Lewis        0.6970

[100 rows x 2 columns]

SyntaxError: ignored